### ISSUE TITLE
The buttons are not clickable when I use Valo theme : Have you an idea ?

### ISSUE THREAD

**Issue by willyUcabanga** [johannest/sticky#1]
Hello,
thank for your addon,  I  tried it,  but when I specified "valo"  theme,  it's not possible to click on the buttons (the buttons are transparencies when there is scroll)

Have you an idea ?

**Comment by johannest** [comment]
Hi, I was able to reproduce the issue. I will investigate this as soon as possible.

**Comment by johannest** [comment]
Should work now, I will update the add-on into directory later

**Comment by willyUcabanga** [comment]
Thank you very much...
